const nftData = [
    {
        nftId: 1,
        image: true,
        color: 'yellowgreen',
        itemName: 'Lofi Lofts #2575',
        creator: 'LofiLofts',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://img.seadn.io/files/359ac32dac8de0225f0159b3d7284dc5.png?fit=max&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'no',
        nearby: 'yes',
        onlyAtStore: true,
        newItem: false,
        customerID: 3
    },
    {
        nftId: 1,
        image: true,
        color: 'yellowgreen',
        itemName: 'Mad Rabbits Riot Club',
        creator: 'Mad Rabbits',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.pinimg.com/736x/10/d2/31/10d2313d6f321909c93b61c332371d0a.jpg',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'no',
        nearby: 'yes',
        onlyAtStore: true,
        newItem: false,
        customerID: null
    },
    {
        nftId: 2,
        image: true,
        color: 'deepskyblue',
        itemName: 'Everydays — The First 5000 Days',
        creator: 'Unknown',
        price: 249.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://99designs-blog.imgix.net/blog/wp-content/uploads/2021/05/merlin_184196631_939fb22d-b909-4205-99d9-b464fb961d32-superJumbo.jpeg?auto=format&q=60&fit=max&w=930',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'limited',
        nearby: 'no',
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },
    {
        nftId: 2,
        image: true,
        color: 'deepskyblue',
        itemName: 'CavemanNFT #3861',
        creator: 'Official CavemanNFT',
        price: 249.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/poF40KemmQv6kZ-WO5Cn1GfXCkpmPS6ixKT_7OyRo7Pf3lCb_0UbPbKS-WslhCXWuo791j9C9-7wADhcAFwk4W5oHhEJjksFRcIwYA?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'limited',
        nearby: 'no',
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },
    {
        nftId: 3,
        image: true,
        color: 'deepskyblue',
        itemName: 'Billionaire Bunny #22',
        creator: 'BillionaireBunnyClub',
        price: 299.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/xmkQQPzlmseUidS_45toc47a1F7GUfRZnXYmmus7HyROgDFDlDdp7GQ1Ts6rliq3I4shy20vh76wXI4RkovZh34mEAUA_cml2OIcXQ?auto=format&w=750',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'yes',
        nearby: "maybe",
        onlyAtStore: true,
        newItem: false,
        customerID: null
    },
    {
        nftId: 3,
        image: true,
        color: 'deepskyblue',
        itemName: 'Second Skin #1111',
        creator: 'ALTAVA Second Skin Metamorphosis',
        price: 159.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/-RYfUcYrV4bUy5WYjz_kE7AxzYEgwXl49wOe5JgNcS5aHRnIJm2irvpd1gcNKozMrN7k-TV9ctxTi1cd1BFG3GP11JxehNEK79XUdA?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'yes',
        nearby: "maybe",
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },
    {
        nftId: 3,
        image: true,
        color: 'deepskyblue',
        itemName: 'GENUINE UNDEAD #1318',
        creator: 'Genuine Undead',
        price: 159.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://img.seadn.io/files/bb5b35bfe08637aa99ad6ed3e2ac74b9.png?fit=max&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'yes',
        nearby: "maybe",
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },
    {
        nftId: 1,
        image: true,
        color: 'yellowgreen',
        itemName: 'Astro Empire',
        creator: 'Space Hoops',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/7WtgMuv7MDwDKkl52GgV7s1hURVDcanpdjzVOvHeIgo_oXcUJO9C-LCpnbw91c0jsc4DDLie6sV9c9QDFnGukLIuhezop0ZEjfES-ZY?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'no',
        nearby: 'yes',
        onlyAtStore: true,
        newItem: false,
        customerID: null
    },
    {
        nftId: 1,
        image: true,
        color: 'yellowgreen',
        itemName: 'JellyDawgs #6675',
        creator: 'JellyDawgs',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/NXIsHFtQMfRhfnARLKb1RbTT2r64te0kbhlySaCLmVYy6ihasNV9fWl_cQX1dlc-ouu5YbJ54-YUQHaslgMU5GCEeogPGaRv-_DCxfc?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'no',
        nearby: 'yes',
        onlyAtStore: true,
        newItem: false,
        customerID: null
    },
    {
        nftId: 2,
        image: true,
        color: 'yellowgreen',
        itemName: 'Liftoff',
        creator: 'Space Hoops',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/7hIKYv6J16h8lp1q5ASKgunBa7dxfGvRfzpMulbg9gqDERA16vdZ2WtBlTGm38-wXgHDcjCWY7zjfCaKedsarjZQ_T-zT715r0C9tm8?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'yes',
        nearby: 'yes',
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },
    {
        nftId: 1,
        image: true,
        color: 'yellowgreen',
        itemName: 'Billionaire Bunny #65',
        creator: 'BillionaireBunnyClub',
        price: 279.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://i.seadn.io/gae/hgR1rnY2xDluGxL5rlPNaBBNMIezzWBkwArRgfKFwjABMSnk1lvluYfQdKVTE70YQhDqXA7eEdGRvi6JFwNpcrGsQe9M7d4QFdAc4w?auto=format&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'no',
        nearby: 'yes',
        onlyAtStore: true,
        newItem: false,
        customerID: null
    },
    {
        nftId: 2,
        image: true,
        color: 'deepskyblue',
        itemName: 'Fidenza #149',
        creator: 'Fidenza by Tyler Hobbs',
        price: 249.99,
        currency: 'ETH',
        currencyLogo: 'https://responsive.fxempire.com/v7/_fxcrypto_/crypto/crypto-logos/eth.png',
        url: 'https://img.seadn.io/files/d8bca7d2a1826459d5f23dd84205ebc2.png?fit=max&w=1000',
        rarityRankNo: 7262,
        rarityTotal: 9710,
        availability: 'limited',
        nearby: 'no',
        onlyAtStore: false,
        newItem: true,
        customerID: null
    },

]

export default nftData;